In [2]:
import numpy as np

In [16]:
list=[1,2,3,4,5]
print(list)
type(list)

[1, 2, 3, 4, 5]


list

In [18]:
print('1D Array')
a=np.array([1,2,3,4,5])
print(a)
type(a)

1D Array
[1 2 3 4 5]


numpy.ndarray

In [20]:
print('2D Array')
b=np.array([[1,2,3,4,5],[9,8,7,6,5]])
print(b)
type(b)

2D Array
[[1 2 3 4 5]
 [9 8 7 6 5]]


numpy.ndarray

In [22]:
print('3D Array')
c=np.array([[[1,2,3,4,5],[9,8,7,6,5],[2,5,6,7,7]]])
print(c)
type(c)

3D Array
[[[1 2 3 4 5]
  [9 8 7 6 5]
  [2 5 6 7 7]]]


numpy.ndarray

In [24]:
print(a.size)
print(b.size)
print(c.size)

5
10
15


In [26]:
print(a.shape)
print(b.shape)
print(c.shape)

(5,)
(2, 5)
(1, 3, 5)


In [30]:
d=np.array([[[1,2,3,4,5],
             [9,8.1,7,6,5],
             [2,5,6,7,7]]])
print(d.dtype)

float64


In [32]:
d.transpose()

array([[[1. ],
        [9. ],
        [2. ]],

       [[2. ],
        [8.1],
        [5. ]],

       [[3. ],
        [7. ],
        [6. ]],

       [[4. ],
        [6. ],
        [7. ]],

       [[5. ],
        [5. ],
        [7. ]]])