In [2]:
import numpy as np

In [4]:
d=np.array([[[1,2,3,4,5],
             [9,8.1,7,6,5],
             [2,5,6,7,7]]])
print(d.dtype)

float64


In [6]:
np.empty((4,4),dtype=float)

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        1.78020169e-306],
       [7.56587585e-307, 1.37961302e-306, 1.05699242e-307,
        1.78022342e-306],
       [1.05700345e-307, 2.31413929e-306, 1.69118108e-306,
        1.69111725e-306],
       [1.69118923e-306, 1.11260144e-306, 6.89812281e-307,
        2.22522596e-306]])

In [10]:
x=np.ones(6)
x

array([1., 1., 1., 1., 1., 1.])

In [14]:
y=np.ones((3,5))
y

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [16]:
z=np.ones((3,5),dtype=int)
z

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [18]:
x=np.zeros(4)
x

array([0., 0., 0., 0.])

In [20]:
y=np.zeros((4,8))
y

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [22]:
a=np.zeros((4,8),dtype=int)
a

array([[0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0]])

In [24]:
m=np.ones((4,8),dtype=str)
m

array([['1', '1', '1', '1', '1', '1', '1', '1'],
       ['1', '1', '1', '1', '1', '1', '1', '1'],
       ['1', '1', '1', '1', '1', '1', '1', '1'],
       ['1', '1', '1', '1', '1', '1', '1', '1']], dtype='<U1')

In [26]:
n=np.ones((4,8),dtype=bool)
n

array([[ True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True]])